import { ArrowRight, ChevronLeft, ChevronRight, ShieldCheck, Truck } from 'lucide-react'
import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import ProductCard from '../components/ProductCard'
import { Button } from '../components/Button'
import { CATEGORIES, HERO_IMAGE, PRODUCTS, PROMO_IMAGE, WORLD_GALLERY } from '../data/products'

export default function Home() {
  const carouselRef = useRef<HTMLDivElement>(null)
  const [email, setEmail] = useState('')
  const [subscribed, setSubscribed] = useState(false)
  const scrollCarousel = (amount: number) => carouselRef.current?.scrollBy({ left: amount, behavior: 'smooth' })
  return <main>
    <section className="relative flex min-h-[min(720px,calc(100vh-110px))] items-end overflow-hidden bg-[#222] text-white"><img src={HERO_IMAGE} alt="Autumn Winter editorial" className="absolute inset-0 h-full w-full object-cover object-center opacity-80" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-black/10" /><div className="relative mx-auto w-full max-w-[1440px] px-6 pb-16 lg:px-12 lg:pb-24"><p className="mb-4 text-[10px] uppercase tracking-[0.3em] text-[#ddd4c5]">Autumn / Winter '26 Editorial</p><h1 className="max-w-2xl font-serif text-5xl font-light leading-[0.95] sm:text-7xl lg:text-8xl">Sculpted Elegance<br /><em className="font-light">&amp; Modern Tailoring</em></h1><div className="mt-8 flex flex-wrap gap-3"><Link to="/shop"><Button>Explore Collection</Button></Link><Link to="/shop?filter=editorial"><Button variant="outline" className="border-white text-white hover:bg-white hover:text-[#121212]">View Lookbook</Button></Link></div></div></section>
    <div className="border-b border-[#E5E2DA] bg-[#F3F1EC] px-5 py-4"><div className="mx-auto flex max-w-[1000px] flex-wrap justify-center gap-x-10 gap-y-3 text-[9px] uppercase tracking-[0.16em] text-[#706F6C]"><span className="flex items-center gap-2"><Truck size={14} strokeWidth={1.2} /> Complimentary delivery</span><span className="flex items-center gap-2"><ShieldCheck size={14} strokeWidth={1.2} /> Secure payments</span><span>Private client services</span><span>Designed in Lagos · Made globally</span></div></div>
    <section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-12 lg:py-28"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-[10px] uppercase tracking-[0.25em] text-[#C5A059]">The edit</p><h2 className="font-serif text-4xl font-light sm:text-5xl">Featured pieces</h2></div><Link to="/shop" className="hidden items-center gap-2 text-[10px] uppercase tracking-[0.18em] sm:flex">View all <ArrowRight size={15} /></Link></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 sm:grid-cols-2 sm:gap-6 lg:grid-cols-4">{PRODUCTS.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div><Link to="/shop" className="mt-10 flex items-center justify-center gap-2 text-[10px] uppercase tracking-[0.18em] sm:hidden">View all <ArrowRight size={15} /></Link></section>
    <section className="bg-[#F3F1EC] py-20 lg:py-28"><div className="mx-auto max-w-[1440px] px-5 lg:px-12"><div className="mb-10 flex items-end justify-between"><div><p className="mb-3 text-[10px] uppercase tracking-[0.25em] text-[#C5A059]">The latest</p><h2 className="font-serif text-4xl font-light sm:text-5xl">New arrivals</h2></div><div className="flex gap-2"><button type="button" aria-label="Previous" onClick={() => scrollCarousel(-360)} className="flex h-9 w-9 items-center justify-center border border-[#D6D2C9]"><ChevronLeft size={16} /></button><button type="button" aria-label="Next" onClick={() => scrollCarousel(360)} className="flex h-9 w-9 items-center justify-center border border-[#D6D2C9]"><ChevronRight size={16} /></button></div></div><div ref={carouselRef} className="flex snap-x gap-4 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{PRODUCTS.slice(4).map((product) => <div key={product.id} className="min-w-[70vw] snap-start sm:min-w-[300px] lg:min-w-[calc(25%-12px)]"><ProductCard product={product} /></div>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-12 lg:py-28"><div className="mb-10 text-center"><p className="mb-3 text-[10px] uppercase tracking-[0.25em] text-[#C5A059]">Explore the house</p><h2 className="font-serif text-4xl font-light sm:text-5xl">Defined by intention</h2></div><div className="grid gap-4 md:grid-cols-3">{CATEGORIES.map((category) => <Link to="/shop" key={category.name} className="group relative aspect-[4/5] overflow-hidden bg-[#F3F1EC]"><img src={category.image} alt={category.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent" /><div className="absolute bottom-7 left-6 text-white"><h3 className="font-serif text-3xl font-light">{category.name}</h3><p className="mt-2 text-[9px] uppercase tracking-[0.16em] text-[#ddd4c5]">{category.description}</p><span className="mt-4 inline-flex items-center gap-2 text-[9px] uppercase tracking-[0.18em]">Discover <ArrowRight size={14} /></span></div></Link>)}</div></section>
    <section id="editorial" className="bg-[#F3F1EC]"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-2"><div className="min-h-[420px] bg-[#ddd] lg:min-h-[620px]"><img src={PROMO_IMAGE} alt="Inside the Tifeh.s atelier" className="h-full w-full object-cover" /></div><div className="flex items-center px-8 py-16 sm:px-16 lg:px-20"><div><p className="mb-5 text-[10px] uppercase tracking-[0.25em] text-[#C5A059]">The atelier</p><h2 className="font-serif text-5xl font-light leading-[0.95] sm:text-6xl">Made for<br /><em>the extraordinary.</em></h2><p className="mt-8 max-w-md text-sm leading-7 text-[#706F6C]">Every Tifeh.s piece begins with a conversation between fabric, form, and the body. Our atelier brings together time-honoured craft and a distinctly modern point of view.</p><Link to="/about" className="mt-8 inline-flex items-center gap-3 border-b border-[#1A1A1A] pb-2 text-[10px] uppercase tracking-[0.2em]">Discover our story <ArrowRight size={15} /></Link></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-12 lg:py-28"><div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><p className="mb-3 text-[10px] uppercase tracking-[0.25em] text-[#C5A059]">From our world</p><h2 className="font-serif text-4xl font-light sm:text-5xl">A closer look</h2></div><div className="grid grid-cols-4 gap-2">{WORLD_GALLERY.slice(0, 8).map((image, index) => <img key={image} src={image} alt={`Tifeh.s editorial ${index + 1}`} className="aspect-square w-full object-cover" />)}</div></div></section>
    <section className="bg-[#121212] px-5 py-20 text-center text-white lg:py-28"><p className="mb-4 text-[10px] uppercase tracking-[0.25em] text-[#C5A059]">Private access</p><h2 className="font-serif text-4xl font-light sm:text-5xl">Private Atelier Invitations</h2><p className="mx-auto mt-5 max-w-md text-xs leading-6 text-[#aaa59c]">Subscribe to receive private preview links, runway access, and seasonal lookbooks.</p>{subscribed ? <p className="mt-8 text-sm text-[#d6c8ac]">Welcome to our private circle.</p> : <form onSubmit={(event) => { event.preventDefault(); setSubscribed(true) }} className="mx-auto mt-8 flex max-w-md border-b border-white/40 pb-2"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="Your email address" className="w-full bg-transparent text-sm text-white outline-none placeholder:text-[#77736d]" /><button type="submit" className="flex items-center gap-2 text-[10px] uppercase tracking-[0.18em]">Subscribe <ArrowRight size={15} /></button></form>}</section>
  </main>
}
