import { Camera, Mail, MapPin } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CURRENCIES } from '../data/products'
import { useShop } from '../context/ShopContext'

export default function Footer() {
  const { currency, setCurrency } = useShop()
  return <footer className="bg-[#121212] px-6 pb-8 pt-16 text-[#F3F1EC] lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-12 border-b border-white/15 pb-14 md:grid-cols-4"><div className="md:col-span-1"><p className="font-serif text-3xl">Tifeh.s</p><p className="mt-1 text-[9px] uppercase tracking-[0.22em] text-[#C5A059]">Collection</p><p className="mt-8 max-w-[220px] text-xs leading-6 text-[#a6a29a]">Sculpted elegance and modern tailoring, created for the moments that matter.</p></div><div><h3 className="mb-5 text-[10px] uppercase tracking-[0.2em] text-[#C5A059]">Client Services</h3><div className="flex flex-col gap-3 text-xs text-[#bcb8af]"><Link to="/contact">Contact Us</Link><Link to="/shipping">Shipping & Returns</Link><Link to="/faq">FAQs</Link><Link to="/orders">Track an Order</Link></div></div><div><h3 className="mb-5 text-[10px] uppercase tracking-[0.2em] text-[#C5A059]">The House</h3><div className="flex flex-col gap-3 text-xs text-[#bcb8af]"><Link to="/#editorial">Our Story</Link><Link to="/shop">Collections</Link><Link to="/atelier">The Atelier</Link><Link to="/journal">Journal</Link></div></div><div><h3 className="mb-5 text-[10px] uppercase tracking-[0.2em] text-[#C5A059]">Legal & Privacy</h3><div className="flex flex-col gap-3 text-xs text-[#bcb8af]"><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms & Conditions</Link><Link to="/accessibility">Accessibility</Link></div></div></div><div className="mx-auto flex max-w-[1440px] flex-col items-start justify-between gap-8 pt-8 sm:flex-row sm:items-center"><div className="flex items-center gap-5 text-[#a6a29a]"><Camera size={16} strokeWidth={1.4} /><span className="text-[10px] uppercase tracking-[0.12em]">X</span><Mail size={16} strokeWidth={1.4} /><MapPin size={16} strokeWidth={1.4} /></div><div className="flex items-center gap-6"><select value={currency} onChange={(event) => setCurrency(event.target.value as keyof typeof CURRENCIES)} className="bg-transparent text-[10px] uppercase tracking-[0.15em] text-[#bcb8af] outline-none">{Object.keys(CURRENCIES).map((code) => <option className="text-[#121212]" key={code}>{code}</option>)}</select><span className="text-[9px] uppercase tracking-[0.15em] text-[#706f6c]">© 2026 Tifeh.s Collection</span></div></div></footer>
}
